### ISSUE TITLE
npm run dev:web启动后无法访问页面

### ISSUE THREAD

**Issue by dycody** [qld-cf/electron-react-tpl#1]
`npm run dev:web`
可以正常启动
访问localhost:9090报错 错误如下
```
ReferenceError: require is not defined
url
webpack:/external "url":1
module.exports = require("url");
```

![url_error](https://user-images.githubusercontent.com/16750803/82880847-8c2b7300-9f71-11ea-8701-61a8c85cdedc.png)

**Comment by qld-cf** [comment]
@GoldWindy 谷歌浏览器不识别nodeApi，这个是之前的，后面这种启动不用

**Comment by GoldWindy** [comment]
有什么办法能让web正常启动的吗？

**Comment by dycody** [comment]
> @GoldWindy 谷歌浏览器不识别nodeApi，这个是之前的，后面这种启动不用

有什么办法能让web正常启动的吗？

**Comment by qld-cf** [comment]
> > @GoldWindy 谷歌浏览器不识别nodeApi，这个是之前的，后面这种启动不用
> 
> 有什么办法能让web正常启动的吗？

注释掉渲染进程中引用nodeapi或者electron的，不过没有必要，APP启动已经是浏览器了 没必要
