### ISSUE TITLE
最好plugin化

### ISSUE THREAD

**Issue by jockey100332** [qld-cf/electron-react-tpl#6]
代码暴露太多了，最好可以做成一个plugin，在umi 中做集成。这样的受众用户可能会更多一些

**Comment by qld-cf** [comment]
@jockey100332 要看受众用户，本身这个tpl就是要给小白入门用的，umi本身就已经集成太多东西，我都打算换普通webpack版本了，随着页面过多，umi本地开发很不舒服的
