### ISSUE TITLE
yarn create @umijs/umi-app 生成的依赖怎么都在dependencies里面了

### ISSUE THREAD

**Issue by gjfei** [qld-cf/electron-react-tpl#8]
![image](https://user-images.githubusercontent.com/33827314/92140153-5127be00-ee43-11ea-8d50-3dd79e23fd82.png)
大佬，我用umi的脚手架yarn create @umijs/umi-app 生成的依赖怎么都在dependencies里面了

**Comment by qld-cf** [comment]
@gjfei umi脚手架默认写到dependencies

**Comment by qld-cf** [comment]
就像你安装依赖  npm i xx, 如果你用-D 或者 --save-dev才能指定到本地devDependencies开发模式，否则都是默认写到dependencies
